"""Optional, read-only, evidence-grounded research copilot."""

from .agent import (
    CopilotError,
    CopilotProvider,
    CopilotProviderError,
    OpenAICompatibleProvider,
    ProviderResponse,
    ProviderToolCall,
    ProviderUsage,
    ResearchCopilot,
    normalize_provider_allowed_hosts,
    normalize_provider_endpoint,
)
from .benchmark import (
    BenchmarkFailure,
    BenchmarkRun,
    BenchmarkUsage,
    run_benchmark,
    write_benchmark_report,
)
from .contracts import (
    COPILOT_DISCLAIMER,
    Citation,
    CopilotAgentIdentity,
    CopilotAnswer,
    CopilotUsage,
    ToolDefinition,
    ToolResult,
    ToolTrace,
)
from .evaluation import (
    CaseEvaluation,
    EvaluationCase,
    EvaluationCorpus,
    EvaluationInputError,
    EvaluationSuite,
    answer_report,
    evaluate_report,
    evaluate_reports,
    load_evaluation_corpus,
)
from .readiness import (
    CopilotReadinessError,
    build_copilot_readiness,
    verify_copilot_readiness,
)
from .review import (
    ReviewInputError,
    append_copilot_reviews,
    benchmark_sha256,
    verify_copilot_review_history,
    write_copilot_review_history,
)
from .tools import ReadOnlyToolset, ToolInputError
from .verification import CopilotVerificationError, verify_copilot_answer_report

__all__ = [
    "Citation",
    "COPILOT_DISCLAIMER",
    "CopilotAgentIdentity",
    "CopilotError",
    "CopilotProvider",
    "CopilotProviderError",
    "CopilotAnswer",
    "CopilotUsage",
    "CaseEvaluation",
    "BenchmarkFailure",
    "BenchmarkRun",
    "BenchmarkUsage",
    "EvaluationCase",
    "EvaluationCorpus",
    "EvaluationInputError",
    "EvaluationSuite",
    "ReviewInputError",
    "OpenAICompatibleProvider",
    "ProviderResponse",
    "ProviderToolCall",
    "ProviderUsage",
    "ReadOnlyToolset",
    "ResearchCopilot",
    "ToolDefinition",
    "ToolInputError",
    "ToolResult",
    "ToolTrace",
    "CopilotVerificationError",
    "answer_report",
    "evaluate_report",
    "evaluate_reports",
    "load_evaluation_corpus",
    "normalize_provider_endpoint",
    "normalize_provider_allowed_hosts",
    "run_benchmark",
    "write_benchmark_report",
    "append_copilot_reviews",
    "benchmark_sha256",
    "verify_copilot_review_history",
    "write_copilot_review_history",
    "verify_copilot_answer_report",
    "CopilotReadinessError",
    "build_copilot_readiness",
    "verify_copilot_readiness",
]
